end_point = "https://api.meson.network"
https_port = 443
token = ""

upgrade_keep=[
  "https_port",
  "token",
  "cache.folder",
  "cache.size",
]

[log]
  level = "INFO"

[cache]
  folder = "./m_cache"
  size = 30

